### ISSUE TITLE
Presentaciones

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Curso-JS-para-desarrolladores-web_ed8#1]
Hola!

Usemos este espacio para conocernos un poco más... :-)

Recordad que estos _issues_ nos permiten abrir y participar en debates, compartir recursos, plantear preguntas y muchas cosas más! 

Podemos usar [Markdown](https://guides.github.com/features/mastering-markdown/) para salirnos del texto plano y enriquecer nuestras aportaciones.

**Comment by CarlosDiazGirol** [comment]
Mi Nombre es Carlos Díaz Girol, Tengo 34 años y durante más de 10 años llevo trabajando en internet. 
Todo comenzó con un curso de diseño gráfico publicitario y a partir de ahí me fui formando en distintas áreas del diseño y la maquetación web. Además de introducirme en animación flash (¡qué antiguo!), la edición de vídeo y la base del modelado 3D. 
Actualmente soy diseñador y maquetador web con HTML5 y CSS3 realizando las webs desde cero, sin frameworks, junto con un programador (woman.es, revistacuore.com, revistaviajar.es y en breve sacaremos el rediseño de autohebdosport.es). Además soy trafficker (gestor publicidad online) en la misma empresa con DFP, y ADX para la publicidad programática para el área de revistas (. 
Mi experiencia siempre ha sido en los departamentos técnicos, de marketing y comerciales. Mi experiencia laboral se ha desarrollado en Telefónica, Orange, Focus Ediciones, HNA, Carrefour e-commerce y actualmente Grupo Zeta.
Así que hago el curso de javascript para mejorar mi perfil y seguir haciendo trucos en internet.

**Comment by jmsenior** [comment]
Buenas ! Mi nombre es José Manuel, tengo 34 años, soy de Cádiz, y empecé hace mucho tiempo como diseñador gráfico hasta que empecé a indagar y empezar en el mundo del desarrollo web hace años, principalmente he estado trabajando con HTML y CSS, pero mis referencias con JS eran muy sencillas con jQuery y solo conseguía hacer pocas utilidades. Lo más reciente que he trabajado ha sido con WebVR, pero estoy "pelao" de Javascript, tengo algunos conocimientos, pero me gustaría empezar de cero con este curso para poder asentar bien los conocimientos para poder aprender más cosas en un futuro, como por ejemplo Angular o implementarlo en más cosas (aplicaciones, juegos, animaciones...etc).

**Comment by JPalomares** [comment]
Salu2,

Me llamo Javier, tengo 26 años y trabajo para el departamento de infraestructura informática en una multinacional (virtualización, etc..).

En mi tiempo libre me dedico a lo que me gusta y tengo una pequeña empresa de diseño web y gráfico 
( www.beaware.es ).

Me apunté a este curso debido a que quiero seguir avanzando con mis conocimientos en programación web para poder captar nuevos clientes y salir un poco de la web básica, espero que aprendamos mucho y lo pasemos bien! 👍

**Comment by Dhelgue** [comment]
Hola!

Soy **Daniel Helguera**, hasta el momento en éste issue el mayor, **(35 años)** .  Aunque mi formación fue la *Educación Física* mi desarrollo profesional se recondujo hacia la banca, y los últimos 3 años dediqué mi tiempo y esfuerzo al *social Media* en una de las principales entidades bancarias del país, para terminar gestionando su web, coordinar su marketing digital y terminando con la transformación en una nueva entidad (branding, desarrollo de nueva web, testing, etc.). Después del lanzamiento de la nueva marca y horas de trabajo decidieron recompensarme con un *hasta la vista baby* 👋

Desde ese día he reconducido mi carrera profesional hacia el desarrollo front en @Fictizia de la mano de @ancoar. 

Creo que **JavaScript** era la continuación idónea al máster que estoy terminando, y quién sabe si el nexo con futuros cursos de *JS Avanzado, Ángular 2, Node.JS...* 

Con ganas de más, nos vemos pronto 👍

**Comment by Vickysolo** [comment]
Hola! Yo soy Vicky y tengo 31 años.

Llevo 10 años trabajando con páginas web. Empecé gestionando contenidos en una web de viajes, y más tarde trabajé como Community Manager y ayudante SEO en una agencia, pero  lo que siempre me gustó fue el desarrollo web, así que decidí hacer un curso y dedicarme a ello.

Actualmente trabajo en un mayorista informático, donde me encargo del diseño y maquetación de la Web y la Newsletter (entre otras cosas).

Mis conocimientos de JavaScript son prácticamente nulos, por eso me decidí a hacer este curso. Para complementar mi perfil y así poder afrontar nuevos retos.

Y aquí estoy, con muchas ganas de aprender y mejorar  ☺️

**Comment by kgrafico** [comment]
Hooolaa!

Mi nombre es Karolina, y tengo 24 años. Me gradué el año pasado en Diseño gráfico en la ESD Madrid, nos han formado para realizar cualquier proyecto digital; Fue donde conocí la programación web y me formé durante los 4 años. El año pasado estudié un Master de Marketing financiado por una multinacional. Paralelamente a estas últimas desde 1 de carrera empecé a introducirme en el mundillo laboral pasando por diseños de branding en gastrobares de Madrid, hasta varias multinacionales conocidas. 

Actualmente estoy en un grupo bodeguero del cual he tenido la oportunidad de participar en el rediseño web, creación de etiquetas, entre otras ... he visto la demanda para implementar una tienda online en mi trabajo. Por ello decidí lanzarme a seguir desarrollando mis conocimientos en programación. 

No os quiero aburrir más jaja y espero conoceros a tod@s y disfrutar de las clases de JS! 

:) 

K.

**Comment by JuanCano88** [comment]
Hola a todos.
Mi nombre es Juan, tengo 29 años y vivo en Madrid desde hace 3.
Actualmente trabajo en el departamento de Marketing Digital de una conocida empresa francesa diseñando webs para diversas operaciones comerciales. Estudié Comunicación Audiovisual en la Universidad de Burgos y desde que terminé la carrera me introduje en el mundo del diseño gráfico y web. Hasta el momento siempre he ido aprendiendo de forma autodidacta, pero lo intenté con javaScript y me resultó muy difícil aprender por mi propia cuenta, por eso estoy en este curso.
Nos vemos en las clases :)
